name: GitHub Actions Demo - Expressions

on:
  push:
    branches: [ expressions ]
  pull_request:
    branches: 
      - 'express**'

env:
  run_step: 'true'

jobs:
  Run-Job-Only-On-Push:
    if: ${{ github.event_name == 'push'  }}
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
         echo "ğŸ This job's status is ${{ job.status }}."

  Run-Job-Only-On-PR:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
         echo "ğŸ This job's status is ${{ job.status }}."

  Run-Job-Always:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Run Step only on Push'
        if: ${{ github.event_name == 'push' && env.run_step == 'true' }}
        run: |
         echo "Triggered by PUSH!"

      - name: 'Run Step only on Pull Request'
        if: ${{ github.event_name == 'pull_request' }}
        run: |
         echo "Triggered by PR!"
